export const LOAD_ALL_NETWORKS = "LOAD_ALL_NETWORKS";

export const LOAD_NETWORK_CONNECTION_STATUS =
  "LOAD_NETWORK_CONNECTION_STATUS_REQUESTING";
export const LOAD_NETWORK_CONNECTION_STATUS_REQUESTING =
  "LOAD_NETWORK_CONNECTION_STATUS_REQUESTING";
export const LOAD_NETWORK_CONNECTION_STATUS_SUCCESS =
  "LOAD_NETWORK_CONNECTION_STATUS_SUCCESS";
export const LOAD_NETWORK_CONNECTION_STATUS_FAILURE =
  "LOAD_NETWORK_CONNECTION_STATUS_FAILURE";
